### ISSUE TITLE
NPE when running AWS batch

### ISSUE THREAD

**Issue by takecare** [novoda/github-reports#66]
We've seen an NPE in a lambda instance when running the batch. Here's the stacktrace:

```
The job with name "xyz" has failed because of an error.

java.lang.NullPointerException
        at com.novoda.github.reports.lambda.issue.TransformToRepositoryIssueEvent.lambda$call$1(TransformToRepositoryIssueEvent.java:43)
        at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:66)
        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
        at rx.Subscriber.setProducer(Subscriber.java:211)
        at rx.internal.operators.OperatorMap$MapSubscriber.setProducer(OperatorMap.java:99)
        at rx.internal.operators.OperatorMap$MapSubscriber.setProducer(OperatorMap.java:99)
        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:8759)
        at rx.Observable.subscribe(Observable.java:8726)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:440)
        at rx.observables.BlockingObservable.first(BlockingObservable.java:163)
        at com.novoda.github.reports.lambda.worker.AmazonWorkerHandler.collectDerivedMessagesFrom(AmazonWorkerHandler.java:148)
        at com.novoda.github.reports.lambda.worker.AmazonWorkerHandler.handleQueueMessage(AmazonWorkerHandler.java:71)
        at com.novoda.github.reports.lambda.worker.AmazonWorkerHandler.handleQueueMessage(AmazonWorkerHandler.java:36)
        at com.novoda.github.reports.batch.worker.BasicWorker.handleQueueMessage(BasicWorker.java:142)
        at com.novoda.github.reports.batch.worker.BasicWorker.doWorkAndHandleErrors(BasicWorker.java:111)
        at com.novoda.github.reports.batch.worker.BasicWorker.doWork(BasicWorker.java:95)
        at com.novoda.github.reports.lambda.Lambda.handle(Lambda.java:45)
        at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:547)
        at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:1139)
        at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:285)
        at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:57)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:94)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: retrofit2.Response.class
        at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:109)
        at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:70)
        ... 47 more

```

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
